// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtOOUwJNbfXJDTqckUajflWbyBm5A4WTU',
    appId: '1:387574737808:web:8fcfa48453bae4b2ade115',
    messagingSenderId: '387574737808',
    projectId: 'planty-5e68b',
    authDomain: 'planty-5e68b.firebaseapp.com',
    storageBucket: 'planty-5e68b.appspot.com',
    measurementId: 'G-5GKBF6VRN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuJqvnuxo1ZLzwJpnPzmvKD0RBpNZOy7M',
    appId: '1:387574737808:android:cb6be1de1563e587ade115',
    messagingSenderId: '387574737808',
    projectId: 'planty-5e68b',
    storageBucket: 'planty-5e68b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeB88nR1i_c8Bpkfog-Ll7dBVjQOhPNcM',
    appId: '1:387574737808:ios:b0d58bc898ef4f14ade115',
    messagingSenderId: '387574737808',
    projectId: 'planty-5e68b',
    storageBucket: 'planty-5e68b.appspot.com',
    iosBundleId: 'com.example.planty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeB88nR1i_c8Bpkfog-Ll7dBVjQOhPNcM',
    appId: '1:387574737808:ios:85ba2ca643f39de1ade115',
    messagingSenderId: '387574737808',
    projectId: 'planty-5e68b',
    storageBucket: 'planty-5e68b.appspot.com',
    iosBundleId: 'com.example.planty.RunnerTests',
  );
}
